name: Build Debian Images
on: [workflow_dispatch]

env:
  NODE_OPTIONS: "--max_old_space_size=8048"

jobs:
  build_amd64:
    name: Build Package for amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Minio CLI
      run: wget https://dl.min.io/client/mc/release/linux-amd64/mc && chmod +x ./mc && ./mc alias set cdn https://cdn.makepro-x.com ${{ secrets.AWS_ACCESS_KEY_ID }} ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Install required dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libasound2-dev pkg-config libudev-dev libusb-1.0-0-dev
    - name: Build
      id: build
      run: |
        git clone "https://${{secrets.GH_ACCESS_TOKEN}}@github.com/makeproaudio/glue.git" && cd glue
        node setup.js
        cd packages/glue-ui && npm run build
        cd ../Glue && npm run build && node build-debian-package.js amd64
    - name: Upload .deb
      run: ./mc cp glue/debian-packages/${{steps.build.outputs.filename}} cdn/glue-deb-packages/${{steps.build.outputs.filename}}
  build_arm64_and_armv7:
    name: Build Package for ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [aarch64, armv7]
    steps:
    - uses: actions/checkout@master
    - name: Install Minio CLI
      run: wget https://dl.min.io/client/mc/release/linux-amd64/mc && chmod +x ./mc && ./mc alias set cdn https://cdn.makepro-x.com ${{ secrets.AWS_ACCESS_KEY_ID }} ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Build
      uses: uraimo/run-on-arch-action@v2.1.1
      id: build
      with:
        arch: ${{ matrix.arch }}
        distro: ubuntu18.04
        env: |
          NODE_OPTIONS: --max_old_space_size=8048
        setup: |
          mkdir -p "${PWD}/artifacts"
        dockerRunArgs: |
          --volume "${PWD}/artifacts:/artifacts"
        install: |
          apt-get update && apt-get install -y curl git libasound2-dev pkg-config libudev-dev libusb-1.0-0-dev
          curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
          apt-get install -y nodejs
          npm install --global yarn
        githubToken: ${{ github.token }}
        run: |
          git clone "https://${{secrets.GH_ACCESS_TOKEN}}@github.com/makeproaudio/glue.git" && cd glue
          node setup.js
          cd packages/glue-ui && npm run build
          cd ../Glue && npm run build && node build-debian-package.js ${{ fromJSON('{"aarch64": "arm64", "armv7": "armv7"}')[matrix.arch] }}
    - name: Upload .deb
      run: ./mc cp artifacts/${{steps.build.outputs.filename}} cdn/glue-deb-packages/${{steps.build.outputs.filename}}