name: Build Debian Images
on: [workflow_dispatch]

jobs:
  build_x64:
    name: Build Package for x64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install Minio CLI
      run: wget https://dl.min.io/client/mc/release/linux-amd64/mc && chmod +x ./mc && ./mc alias set cdn https://cdn.makepro-x.com ${{ secrets.AWS_ACCESS_KEY_ID }} ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Build
      run: |
        git clone "https://${{secrets.GH_ACCESS_TOKEN}}@github.com/makeproaudio/glue.git" && cd glue && git checkout debian-packages
        yarn
        cd packages/glue && node build-debian-package.js x64
    # - name: Upload .deb
    #   run: ./mc cp packages/Glue/${{steps.bundle.outputs.filename}} cdn/glue-deb-packages/${{steps.bundle.outputs.filename}}
  build_arm64_and_armv7:
    name: Build Package for ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [aarch64, armv7]
    steps:
    - uses: actions/checkout@master
    - name: build
      uses: uraimo/run-on-arch-action@v2.1.1
      id: emulator
      with:
        arch: ${{ matrix.arch }}
        distro: ubuntu18.04
        install: |
          apt update && apt install wget
          wget https://dl.min.io/client/mc/release/linux-amd64/mc && chmod +x ./mc
        githubToken: ${{ github.token }}
        run: |
          ./mc alias set cdn https://cdn.makepro-x.com ${{ secrets.AWS_ACCESS_KEY_ID }} ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          git clone "https://${{secrets.GH_ACCESS_TOKEN}}@github.com/makeproaudio/glue.git" && cd glue && git checkout debian-packages
          yarn
          cd packages/glue && node build-debian-package.js ${{ matrix.arch }}
    # - name: Upload .deb
    #   run: ./mc cp packages/Glue/${{steps.bundle.outputs.filename}} cdn/glue-deb-packages/${{steps.bundle.outputs.filename}}